import 'package:hive/hive.dart';

part 'user.g.dart'; // generated by build_runner

@HiveType(typeId: 0)
class AppUser extends HiveObject {
  @HiveField(0)
  String email;

  @HiveField(1)
  String password;

  @HiveField(2)
  String role; // VOLUNTEER or ADMIN

  AppUser({
    required this.email,
    required this.password,
    required this.role,
  });
}
